language: java
jdk:
  - oraclejdk8
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - git clone https://github.com/res-x/resx.git
  - cd resx/resx-parent && mvn install && cd ../../
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
  - nvm install 5.0
  - nvm use 5.0