language: java
jdk:
  - oraclejdk8
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - git clone https://github.com/res-x/resx.git
  - cd resx/resx-parent && mvn install && cd ../../